---
- hosts: web
  become: true
  tasks:
    - name: Pull the latest Docker image from Docker Hub
      docker_image:
        name: "node-docker-app"  # Change this to your image name if available
        tag: "latest"
        source: pull

    - name: Stop and remove existing container if any
      docker_container:
        name: node-docker-app
        state: absent

    - name: Run the Docker container
      docker_container:
        name: node-docker-app
        image: "node-docker-app"  # Change this to your image name if available
        state: started
        restart_policy: always
        published_ports:
          - "80:2000"

