name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Change to a stable version if needed

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy code to EC2 instance using SSH
        uses: appleboy/scp-action@master
        with:
          source: "./"  # Copy the entire directory
          target: "/home/ubuntu/devops_project"  # Path to the project directory on the EC2 instance
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Verify Files on EC2 (Debugging Step)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ls -l /home/ubuntu/devops_project

      - name: Deploy to EC2 and update Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DOCKER_BUILDKIT=1

            # Navigate to the project directory
            cd /home/ubuntu/devops_project

            # Check if Dockerfile exists
            if [ ! -f Dockerfile ]; then
              echo "Dockerfile not found!" >&2
              exit 1
            fi

            # Remove the old container if it exists
            docker stop node-docker-app || true
            docker rm node-docker-app || true

        # Remove the old image to avoid pulling from a remote registry
            docker rmi node-docker-app || true

# Build the Docker image with the updated code
            docker build -t node-docker-app:v1 .

            # Run the new container with the latest image
            docker run -d -p 80:2000 --name node-docker-app node-docker-app
