name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Copy code to EC2 instance using SSH
        uses: appleboy/scp-action@master
        with:
          source: "./" # Copy the whole directory
          target: "/home/ubuntu/devops_project/node-docker-app" # Path on the EC2 instance
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Debug SSH key
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"


      - name: Deploy to EC2 and build Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/devops_project/node-docker-app
            docker build -t node-docker-app .
            docker stop node-docker-app || true
            docker rm node-docker-app || true
            docker run -d -p 80:2000 --name node-docker-app node-docker-app

